---
# tasks file for Ansible-Docker-YumRepo-Role---
- yum_repository:
        file: "{{ item.file }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        enabled: "{{ item.enabled }}"
        gpgcheck: "{{ item.gpgcheck }}"
        gpgkey: "{{ item.gpgkey }}"
  loop: 
        - file : "docker-ce-repo"
          name: "DockerRepo" 
          description: "Repository for configuring Docker Engine on Base OS"
          baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
          enabled: 1
          gpgcheck: no
          gpgkey: ""
        - file: "docker-ce-repo"
          name: "docker-ce-stable"
          description: "Docker CE Stable - $basearch"
          baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
          enabled: 1
          gpgcheck: 1
          gpgkey: https://download.docker.com/linux/centos/gpg
        - file: "docker-ce-repo"
          name: "docker-ce-stable-debuginfo"
          description: "Docker CE Stable - Debuginfo $basearch"
          baseurl: https://download.docker.com/linux/centos/$releasever/debug-$basearch/stable
          enabled: 0
          gpgcheck: 1
          gpgkey: https://download.docker.com/linux/centos/gpg
        - file: "docker-ce-repo"
          name: "docker-ce-stable-source"
          description: "Docker CE Stable - Sources"
          baseurl: https://download.docker.com/linux/centos/$releasever/source/stable
          enabled: 0
          gpgcheck: 1
          gpgkey: https://download.docker.com/linux/centos/gpg
        - file: "docker-ce-repo"
          name: "docker-ce-nightly"
          description: "Docker CE Nightly - $basearch"
          baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/nightly
          enabled: 0
          gpgcheck: 1
          gpgkey: https://download.docker.com/linux/centos/gpg
        - file: "docker-ce-repo"
          name: "docker-ce-nightly-source"
          description: "Docker CE Nightly - Sources"
          baseurl: https://download.docker.com/linux/centos/$releasever/source/nightly
          enabled: 0
          gpgcheck: 1
          gpgkey: https://download.docker.com/linux/centos/gpg
- name: "Installing Docker-CE"
  command: "yum install -y  docker-ce --nobest"
- name: starting docker services
  service:
          name: "docker"
          state: started
          enabled: yes
- package:
        name: "python3"
        state: present
- pip:
        name: "docker-py >= 1.7.0"

